# Generated by Django 3.2.5 on 2021-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(max_length=100)),
                ('aurther', models.CharField(max_length=100)),
                ('book_code', models.IntegerField(max_length=10)),
            ],
        ),
    ]
