# Generated by Django 3.2.6 on 2021-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
