# Generated by Django 3.2.6 on 2021-08-29 20:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_uploadfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/hiader/Pictures'), upload_to=''),
        ),
    ]
