# Generated by Django 3.2.6 on 2021-09-01 01:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_uploadfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
