# Generated by Django 3.2.6 on 2021-09-01 01:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upload_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
