# Generated by Django 3.2.6 on 2021-09-01 01:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadimg_to', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/hiader/Pictures'), upload_to='')),
            ],
        ),
    ]
