# Generated by Django 3.2.6 on 2021-09-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_uploadimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_name',
        ),
    ]
