# Generated by Django 3.2.6 on 2021-09-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_rename_email_user_email_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_name',
            field=models.EmailField(max_length=254),
        ),
    ]
