# Generated by Django 3.2.6 on 2021-09-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_user_email_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_name',
            new_name='email',
        ),
    ]
